<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace backend\components;

/**
 * Description of MyUploadedFile
 *
 * @author zeng
 */
class MyUploadedFile extends \yii\web\UploadedFile {
    public function getSaveName() {
        return uniqid();
    }

    public function saveAs($file, $deleteTempFile = true)
    {
        Helper::dir_create($file);
        return parent::saveAs($file, $deleteTempFile); // TODO: Change the autogenerated stub
    }

    public function saveThumb($srcfile,$dstfile){
        Helper::dir_create($dstfile);
        \yii\imagine\Image::thumbnail($srcfile, 160, 120)
            ->save($dstfile);
    }
}
